server:
  port: 8080

spring:
  application:
    name: kickr-server

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  datasource:
    url: jdbc:postgresql://localhost:5432/kickr_db
    username: kickr_user
    password: kickr_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

jwt:
  secret: ${JWT_SECRET:default_jwt_secret_must_be_changed_in_production_1234567890}
football:
  api:
    key: ${FOOTBALL_API_KEY:none}


logging:
  level:
    root: INFO
    com.kickr_server: DEBUG
    org.hibernate.SQL: DEBUG
    org.springframework.security: DEBUG
    # DÃ©sactiver les logs verbeux de RMI/JMX
    sun.rmi: WARN
    javax.management: WARN
    sun.rmi.transport: WARN
    sun.rmi.loader: WARN

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true

resilience4j:
  ratelimiter:
    instances:
      authRateLimiter:
        limitForPeriod: 100
        limitRefreshPeriod: 10s
        timeoutDuration: 1s
      feedRateLimiter:
        limitForPeriod: 100
        limitRefreshPeriod: 10s
        timeoutDuration: 200ms
      userRateLimiter:
        limitForPeriod: 100
        limitRefreshPeriod: 10s
        timeoutDuration: 500ms
      userMatchRateLimiter:
        limitForPeriod: 100
        limitRefreshPeriod: 10s
        timeoutDuration: 500ms
      followRateLimiter:
        limitForPeriod: 100
        limitRefreshPeriod: 10s
        timeoutDuration: 500ms
