server:
  port: 8080

spring:
  application:
    name: kickr-server

  datasource:
    url: jdbc:postgresql://localhost:5432/kickr_db
    username: kickr_user
    password: kickr_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

jwt:
  secret: ${JWT_SECRET}
football:
  api:
    key: ${FOOTBALL_API_KEY}


logging:
  level:
    com.ampara: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true



resilience4j:
  ratelimiter:
    instances:
      authRateLimiter:
        limitForPeriod: 5
        limitRefreshPeriod: 30s
        timeoutDuration: 1s
      feedRateLimiter:
        limitForPeriod: 20
        limitRefreshPeriod: 10s
        timeoutDuration: 200ms
      userRateLimiter:
        limitForPeriod: 10
        limitRefreshPeriod: 10s
        timeoutDuration: 500ms
      userMatchRateLimiter:
        limitForPeriod: 10
        limitRefreshPeriod: 10s
        timeoutDuration: 500ms
      followRateLimiter:
        limitForPeriod: 5
        limitRefreshPeriod: 10s
        timeoutDuration: 500ms




