server:
  port: 8080

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  
  application:
    name: kickr-server

  data:
    web:
      pageable:
        serialization-mode: via-dto

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  datasource:
    url: jdbc:postgresql://localhost:5432/kickr_db
    username: kickr_user
    password: kickr_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

jwt:
  secret: ${JWT_SECRET:default_jwt_secret_must_be_changed_in_production_1234567890}
  expiration: ${JWT_EXPIRATION:900} # 15 minutes by default
football:
  api:
    key: ${FOOTBALL_API_KEY:none}


logging:
  level:
    root: INFO
    com.kickr_server: INFO
    org.hibernate.SQL: WARN

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when_authorized
    metrics:
      enabled: true



resilience4j:
  ratelimiter:
    instances:
      authRateLimiter:
        limitForPeriod: 5
        limitRefreshPeriod: 30s
        timeoutDuration: 1s
      feedRateLimiter:
        limitForPeriod: 20
        limitRefreshPeriod: 10s
        timeoutDuration: 200ms
      userRateLimiter:
        limitForPeriod: 10
        limitRefreshPeriod: 10s
        timeoutDuration: 500ms
      userMatchRateLimiter:
        limitForPeriod: 10
        limitRefreshPeriod: 10s
        timeoutDuration: 500ms
      followRateLimiter:
        limitForPeriod: 5
        limitRefreshPeriod: 10s
        timeoutDuration: 500ms




