services:
  postgres:
    image: postgres:15-alpine
    container_name: kickr-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - kickr-network

  backend:
    image: ghcr.io/${GITHUB_REPOSITORY}/backend:latest
    container_name: kickr-server
    expose:
      - "8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
      - FOOTBALL_API_KEY=${FOOTBALL_API_KEY}
      - ADMIN_NAME=${ADMIN_NAME}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    mem_limit: 1024M
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - kickr-network
      - proxy-network

  client:
    image: ghcr.io/${GITHUB_REPOSITORY}/client:latest
    container_name: kickr-client
    restart: always
    depends_on:
      - backend
    networks:
      - kickr-network
      - proxy-network

networks:
  kickr-network:
  proxy-network:
    external: true 

volumes:
  postgres_data: